### PR TITLE
Fixed issue with DB not adding new students.

### PR DESCRIPTION
**Pull request by LegendArtur**

### CODE REVIEW

**Review by justncheng — APPROVED** [review]

**Review by lo-vil — COMMENTED** [review]
Great Work Artur, Truly Outstanding! Keep up the good work ;)

PS Why are you not returning my calls? I've left you 22 voice messages, did I do something wrong?!

**Review by yasminehilout — APPROVED** [review]
Thank you. Keep up the good work!

**Review by justncheng — APPROVED** [review]
great job great job great job great job great job great job great job great job great job great job great job great job great job great job great job great job great job great job great job great job great job great job great job great job great job great job great job great job great job great job great job great job great job great job great job great job great job great job great job great job great job great job great job great job great job great job great job great job

**Review by lo-vil — APPROVED** [review]
Was it something I said or did? I've stopped by your place twice now and still no answer. I thought we had something good going last time at dinner. Talk to me baby.

**Pull request merged**
